<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  
  <ItemGroup>
    <None Remove="Assets\logo_32.ico" />
    <None Remove="Assets\logo_512.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="CommunityToolkit.Mvvm" />

    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" />
    <PackageReference Include="Irihi.Ursa" />
    <PackageReference Include="Irihi.Ursa.Themes.Semi" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Semi.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SuperPassword.BLL\SuperPassword.BLL.csproj" />
    <ProjectReference Include="..\SuperPassword.Entity\SuperPassword.Entity.csproj" />
    <ProjectReference Include="..\SuperPassword.Setting\SuperPassword.Config.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
    <Folder Include="Common\" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Update="Assets\logo_32.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\logo_512.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </AvaloniaResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\SingleView.axaml.cs">
      <DependentUpon>SingleView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
