<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Prism.DryIoc" />
    <PackageReference Include="RestSharp" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SuperPassword.BLL\SuperPassword.BLL.csproj" />
    <ProjectReference Include="..\SuperPassword.Entity\SuperPassword.Entity.csproj" />
    <ProjectReference Include="..\SuperPassword.Setting\SuperPassword.Config.csproj" />
  </ItemGroup>

</Project>
